### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
Following your request in the tweet:
http://twitter.com/NeoIghodaro/status/1180935261347340288

Here it is your brand new logo… I've decided to maintain the trend of unDraw to match the package itself. **Hope you like it!** 😄 

image

### CODE REVIEW

**Comment by neoighodaro** [comment]
Love it! Thanks

**Comment by caneco** [comment]
Hello @neoighodaro, all good with the PR? 😇

**Comment by neoighodaro** [comment]
Oh yes, sorry merging now.  Thought i already did

**Comment by caneco** [comment]
@neoighodaro, no problem 💪

**Pull request merged**
